// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_Rz5p6ro8gjgHtUNeXoel5vUq_4Kp_4',
    appId: '1:343310748559:web:33184afda2ebda308799fa',
    messagingSenderId: '343310748559',
    projectId: 'insta-clone-91d8f',
    authDomain: 'insta-clone-91d8f.firebaseapp.com',
    storageBucket: 'insta-clone-91d8f.appspot.com',
    measurementId: 'G-M1DGLZS7P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDi__JV51fXQsnA8k8ZPJXEVihlAk5Lk',
    appId: '1:343310748559:android:fdf590ef3fc7ee848799fa',
    messagingSenderId: '343310748559',
    projectId: 'insta-clone-91d8f',
    storageBucket: 'insta-clone-91d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHl0wmsvpMODjgK7cnDuLEFCoLD1v7Nss',
    appId: '1:343310748559:ios:430dc5d1fe5c68768799fa',
    messagingSenderId: '343310748559',
    projectId: 'insta-clone-91d8f',
    storageBucket: 'insta-clone-91d8f.appspot.com',
    iosClientId: '343310748559-49e9evcm6m08jnb9iai5c8klo7b224qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHl0wmsvpMODjgK7cnDuLEFCoLD1v7Nss',
    appId: '1:343310748559:ios:430dc5d1fe5c68768799fa',
    messagingSenderId: '343310748559',
    projectId: 'insta-clone-91d8f',
    storageBucket: 'insta-clone-91d8f.appspot.com',
    iosClientId: '343310748559-49e9evcm6m08jnb9iai5c8klo7b224qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
